### ISSUE TITLE
sanity test

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/yugabyte-datasource#21]
```[tasklist]
### Tasks
- [x] alerting not supported ( update in the plugin,.json ) -- completed in [#24](https://github.com/grafana/yugabyte-datasource/pull/24)
- [x] in the config page, ssl mode dropdown is unusable/disabled. please check -- completed in [#17](https://github.com/grafana/yugabyte-datasource/pull/17)
- [x] in the config page, password field looks like optional. ( no * like username -- see comment
- [ ] healthcheck : with empty address it is complaining no port instead of invalid address
- [ ] healthecheck: when only the URL filled, I get "plugin healthcheck failed" but no hint why it failed.. incorrect password also behaves the same.
- [x] query editor: when I select table, the column name selector need to show loading indicator. -- see comment
- [x] query editor: "run query" button always shows me an error. -- completed in [#28](https://github.com/grafana/yugabyte-datasource/pull/28)
```
